opt_in_rules:
  - all

disabled_rules:
  - anonymous_argument_in_multiline_closure
  - anyobject_protocol
  - closure_body_length
  - cyclomatic_complexity
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - function_body_length
  - function_default_parameter_at_end
  - inert_defer
  - missing_docs
  - no_grouping_extension
  - no_magic_numbers
  - number_separator
  - object_literal
  - one_declaration_per_file
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - required_deinit
  - shorthand_operator
  - sorted_enum_cases
  - sorted_imports
  - strict_fileprivate
  - trailing_closure
  - type_body_length
  - type_name
  - unused_capture_list
  - vertical_whitespace_between_cases

attributes:
  always_on_same_line: ["@IBAction", "@IBOutlet", "@NSManaged", "@objc", "@inlinable", "@Persisted"]

file_length:
  warning: 1000
  error: 1000
  ignore_comment_only_lines: true

file_name:
  excluded: ["Foundation+Extension.swift", "UIKit+Extension.swift", "RxCocoa+Extension.swift", "RxFlow+Extension.swift", "SnapKit+Extension.swift", "PreviewModels.swift", "Reader.swift"]

file_types_order:
  order: [[main_type], [extension], [supporting_type], [preview_provider], [library_content_provider]]

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded: ["w", "h", "x", "y"]

indentation_width:
  indentation_width: 2
  include_multiline_strings: false

implicit_return:
  included: [closure, getter, initializer, subscript]

line_length:
  warning: 200
  error: 10000
  ignores_function_declarations: true
  ignores_interpolated_strings: true

nesting:
  type_level:
    warning: 2

type_contents_order:
  order: [[case], [type_alias, associated_type], [type_property], [instance_property], [ib_inspectable], [ib_outlet], [initializer], [deinitializer], [type_method], [view_life_cycle_method], [ib_action], [other_method], [subscript], [subtype]]

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error
  no_direct_standard_out_logs:
    name: "Writing log messages directly to standard out is disallowed"
    regex: "(\\bprint|\\bdebugPrint|\\bdump|Swift\\.print|Swift\\.debugPrint|Swift\\.dump)\\s*\\("
    match_kinds:
    - identifier
    message: "Don't commit `print(…)`, `debugPrint(…)`, or `dump(…)` as they write to standard out in release. Either log to a dedicated logging system or silence this warning in debug-only scenarios explicitly using `// swiftlint:disable:next no_direct_standard_out_logs`"
    severity: warning
